### ISSUE TITLE
ContextErrorException: Warning: DOMDocument::loadXML(): Empty string supplied as input

### ISSUE THREAD

**Issue by salletti** [BeSimple/BeSimpleSoap#62]
Hi, 

I can't download correctly my wsdl. I have the follow error when i try to call the client:

> ContextErrorException: Warning: DOMDocument::loadXML(): Empty string supplied as input in C:\wamp\www\FlexFront\vendor\besimple\soap-client\BeSimple\SoapClient\WsdlDownloader.php line 159

My configuration is: 

```
// app/config_dev.yml

    be_simple_soap:
        clients:
            high_deal_consultation:
                wsdl: http://highdealdev:8080/consultation?wsdl
```

When i call the service in this normal way

`$this->container->get('besimple.soap.client.high_deal_consultation')`

I have the error.

However the wsdl is accessible. Any idea? 

Tanks, 

Stefano
